import './globals.css'
import 'react-toastify/dist/ReactToastify.css'

import type { Metadata } from 'next'
import { Lexend_Deca as LexendDeca } from 'next/font/google'
import { ToastContainer } from 'react-toastify'

const inter = LexendDeca({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-950 text-white ${inter.className}`}>
        <ToastContainer />
        {children}
      </body>
    </html>
  )
}
