import './globals.css'

import type { Metadata } from 'next'
import { Lexend_Deca as LexendDeca } from 'next/font/google'

const inter = LexendDeca({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`bg-slate-950 text-white ${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
